#%RAML 1.0 NamedExample
value:
  pickuplocation : Chennai
  droplocation : Hyderabad
  noofperson : 6
  vehicletype : SUV
  pickuptime : 10:00AM
  passengername : Bala
  vehicleno : TN10AA5674
  status : Booked